- .github/workflows/publish-crates-cargo.yml
- .github/workflows/publish-crates-debian.yml
- .github/workflows/publish-crates-eclipse.yml
- .github/workflows/publish-crates-github.yml
- .github/workflows/publish-crates-homebrew.yml
- .github/workflows/tag-crates.yml
- dist/publish-crates-cargo-main.js
- dist/publish-crates-homebrew-main.js
- dist/tag-crates-main.js
- publish-crates-cargo/action.yml
- publish-crates-debian/action.yml
- publish-crates-eclipse/action.yml
- publish-crates-github/action.yml
- publish-crates-homebrew/action.yml
- src/publish-crates-cargo.ts
- src/publish-crates-debian.ts
- src/publish-crates-eclipse.ts
- src/publish-crates-github.ts
- src/publish-crates-homebrew.ts
- src/tag-crates.ts
- tag-crates/action.yml
Closes https://github.com/eclipse-zenoh/ci/issues/11.
- Rename dry-run to live-run
- Make live-run optional
- Always auto-generate version if not provided
> fix: Make tag-crates less confusing

- dist/publish-crates-cargo-main.js
- dist/tag-crates-main.js
- src/cargo.ts
- src/publish-crates-cargo.ts
Closes https://github.com/eclipse-zenoh/ci/issues/21.
> fix: Persist registry configuration in Cargo config file

- src/publish-crates-debian.ts
- src/publish-crates-eclipse.ts
- src/publish-crates-github.ts
- src/zip.ts
Resolves https://github.com/eclipse-zenoh/ci/issues/25 (follow-up fixes).
> Various follow-up fixes for release workflows

- .github/workflows/release-crates-dockerhub.yml
- .github/workflows/release-crates-ghcr.yml
- publish-crates-docker/Dockerfile
- publish-crates-docker/action.yml
- publish-crates-docker/prepare.bash
Resolves https://github.com/eclipse-zenoh/zenoh/issues/795.
> feat: Add release-crartes-dockerhub/ghcr workflows

- .github/workflows/release-crates-cargo.yml
- .github/workflows/release-crates-debian.yml
- .github/workflows/release-crates-eclipse.yml
- .github/workflows/release-crates-github.yml
- .github/workflows/release-crates-homebrew.yml
Resolves https://github.com/eclipse-zenoh/ci/issues/31.
> fix(workflows/release-crates-*): Set `live-run` to false

- dist/publish-crates-cargo-main.js
- dist/tag-crates-main.js
- src/command.ts
Fixes https://github.com/eclipse-zenoh/ci/issues/45.
> fix: Inherit parent process envrionment in commands

- .github/workflows/release-crates-cargo.yml
- dist/publish-crates-cargo-main.js
- publish-crates-cargo/action.yml
- src/publish-crates-cargo.ts
Resolves https://github.com/eclipse-zenoh/ci/issues/48.
> feat: Support unpublished dependencies in `publish-crates-cargo`

- publish-crates-debian/action.yml
- src/publish-crates-debian.ts
> feat: Support skipping instllation test in publish-crates-debian

- .github/workflows/release-crates-cargo.yml
- .github/workflows/release-crates-dockerhub.yml
- .github/workflows/release-crates-eclipse.yml
- .github/workflows/release-crates-ghcr.yml
- .github/workflows/release-crates-github.yml
- .github/workflows/release-crates-homebrew.yml
- .gitignore
- bump-crates/action.yml
- create-release-branch/action.yml
- dist/publish-crates-cargo-main.js
- publish-crates-docker/action.yml
- publish-crates-eclipse/action.yml
- publish-crates-github/action.yml
- publish-crates-homebrew/action.yml
- src/bump-crates.ts
- src/create-release-branch.ts
- src/publish-crates-cargo.ts
- src/publish-crates-eclipse.ts
- src/publish-crates-github.ts
- src/publish-crates-homebrew.ts
> fix: Align all inputs in action, workflows, modules

- dist/publish-crates-cargo-main.js
- src/publish-crates-cargo.ts
> fix: Use default branch for unpublished Cargo deps

- dist/publish-crates-cargo-main.js
- src/publish-crates-cargo.ts
> fix: Incorrect registry setting when publishing to estuary

- src/git.ts
Resolves https://github.com/eclipse-zenoh/ci/issues/69.
> fix: Trim git-describe output

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
> fix: Incorrect cross ussage predicate

- .github/workflows/sync-lockfiles.yml
This also changes the date format from `%ah` to `%as`.
> fix: Always enable auto-merge in sync-lockfiles

- src/build-crates-standalone.ts
In #87 the repo path was correct but I confused it with the repo name used as part of the artifact name.
> fix: Incorrect artifact name in build-crates-standalone

- dist/bump-crates-main.js
- dist/create-release-branch-main.js
- src/bump-crates.ts
- src/create-release-branch.ts
> fix: Always force push release branch

- src/build-crates-debian.ts
- src/build-crates-standalone.ts
- src/zip.ts
[See this run of zenoh-c's release where the `include` folder is not uploaded](https://github.com/eclipse-zenoh/zenoh-c/actions/runs/8714138993/job/23904239344).
> fix: Support recursive search in `zip.fromDirectory`

- __tests__/cargo.test.ts
- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/build-crates-debian.ts
- src/cargo.ts
- src/toml.ts
The `TOML` constructor introduced in #43 contained a floating promise.
> fix: Floating TOML constructor promise

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/toml.ts
This was supposed to be done in #112.
> chore: Remove `TOML` constructor

- dist/bump-crates-main.js
- dist/create-release-branch-main.js
- dist/publish-crates-cargo-main.js
- src/command.ts
- src/toml.ts
The `value` argument can contain spaces. A lot more commands should be changed to use `exec` instead of `sh` in the future.
> fix: Quote command arguments in toml.ts

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- package-lock.json
- src/cargo.ts
[Some Cargo binaries will fail to run if compiled on OSs with new libc's and used on OSs with older libc's.](https://github.com/eclipse-zenoh/zenoh/actions/runs/8787107981/job/24111632595)
> fix: Include OS release in cargo binary cache key

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
[See this workflow run failure.](https://github.com/eclipse-zenoh/zenoh-plugin-webserver/actions/runs/8896022544/job/24427707314)
> fix: Typo in cargo module ('version' -> 'branch')

- .github/workflows/check-labels.yml
> feat: Add check-labels workflow

- .github/workflows/sync-lockfiles.yml
artifact actions v3 are deprecated
> chore: update artifact actions to v4

- dist/create-release-branch-main.js
- src/git.ts
> fix: Don't use `--single-branch` in `git.cloneFromGitHub`

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
> revert: Don't ignore workspace dev dependencies in `cargo.packages`

- .github/workflows/sync-toolchains.yml
and fix syntax for if workflow call
> fix: typo in matrix attribute

- .github/workflows/check-labels.yml
Bash script failed to identify the proper labels from the PR if it includes the "new feature" label due to the space in the label.
> fix: Update check-labels script

- .github/workflows/sync-lockfiles.yml
Make sure zenoh-c is pointing to the latest zenoh commit
> fix: run cargo update zenoh 

- .github/workflows/sync-lockfiles.yml
- .github/workflows/sync-toolchains.yml
Add Zenoh-ts syncing now that it we have an official repo in eclipse-zenoh
> Add Zenoh-ts lockfile and toolchain sync

- .github/workflows/merge-release-branch.yml
Re-usable workflow to be used as a post-release step.
> feat: add workflow to merge release branch

- .github/workflows/merge-release-branch.yml
See https://github.com/eclipse-zenoh/ci/actions/runs/12830599446/job/35779154838
> chore: fix ident

- .github/workflows/sync-auto-changelog.yml
Add a workflow to sync the relase.yml auto changelog file from the Zenoh repo to the rest of the ecosystem.
> feat: add sync changelog file

- .github/workflows/sync-changelog-config.yml
See https://github.com/eclipse-zenoh/ci/actions/runs/12992046248/job/36230995354
> fix: correct artifact name

- .github/workflows/merge-release-branch.yml
- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- dist/set-git-branch-main.js
- src/set-git-branch.ts
- src/toml.ts
- change toml get to return an empty string in case of non-existent key, instead of returning error code 1
- fix syntax error in compute-branch workflow step
- fix git push to push to new post-release-$version branch
> Fixes for set git branch action 

- .github/workflows/merge-release-branch.yml
- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- dist/set-git-branch-main.js
- src/cargo.ts
- src/set-git-branch.ts
- properly exit when pull request already exist
- fix formatting in conditional
- correct logic to set git/branch on deps
- install dependencies for zenoh-dissector
- change setGitBranch to accept manifestPath directly, so `Cargo.toml.in` can be edited as well.
> More fixes

- dist/set-git-branch-main.js
- src/set-git-branch.ts
Also adds nested Cargo.lock files
> fix: add only the modified Cargo.toml

- dist/set-git-branch-main.js
- src/set-git-branch.ts
so we can use the `**/` glob to git add/commit `Cargo.*` files
> fix: enable shopt -s globstar

- .github/workflows/sync-changelog-config.yml
- .github/workflows/sync-lockfiles.yml
Always add PR to annotation either as created or updated
> fix: Update sync workflows to display PR URL

- dist/publish-crates-cargo-main.js
- src/publish-crates-cargo.ts
Avoid updating dependencies of dependencies during cargo publish
> fix: use --locked with cargo publish

- dist/publish-crates-cargo-main.js
- src/publish-crates-cargo.ts
Replace estuary with cargo check as a publication test.
Partially addresses https://github.com/eclipse-zenoh/zenoh/issues/1832 but ideally the check should be done as part of zenoh CI as well.
> Replace estuary cargo check

- __tests__/cargo.test.ts
- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- dist/set-git-branch-main.js
- src/cargo.ts
Download zenoh-plugin-mqtt release 1.3.0 since the Cargo.lock was changed to version 4
> fix: update Cargo.lock in place

- __tests__/cargo.test.ts
- dist/build-crates-debian-main.mjs
- dist/build-crates-standalone-main.mjs
- dist/bump-crates-main.mjs
- dist/publish-crates-cargo-main.mjs
- dist/publish-crates-debian-main.mjs
- dist/publish-crates-eclipse-main.mjs
- dist/publish-crates-github-main.mjs
- dist/publish-crates-homebrew-main.mjs
- dist/set-git-branch-main.mjs
- src/build-crates-debian.ts
- src/cargo.ts
- src/toml.ts
Lots of workflows depend on it and it'll take too much time to fix the workflows individuall to install toml-cli2 individually
> fix: revert change to install toml-cli2

- .github/workflows/build-crates-debian.yml
- .github/workflows/build-crates-standalone.yml
ubuntu-20.04 runners are being deprecated.
> chore: update ubuntu runners to ubuntu-24.04

- set-git-branch/action.yml
Fix https://github.com/eclipse-zenoh/ci/actions/runs/14259515014/job/39968034066#step:4:20
> fix: refer to correct set-git-branch-main.mjs

- dist/set-git-branch-main.mjs
- src/set-git-branch.ts
avoid interactive commit message step
> fix: add --no-edit to git merge

- __tests__/cargo.test.ts
- dist/set-git-branch-main.mjs
- src/cargo.ts
Set git/branch config in build-dependencies (e.g. zenoh-c) and workspace.metadata.bin (e.g. zenoh-ts)
> fix: handle build-deps and metadata.bin

- dist/build-crates-standalone-main.mjs
- dist/create-release-branch-main.mjs
- src/git.ts
so extract only the repo to use as the path for git reset
> fix: repo is actually org/repo

- .github/workflows/release-debian-repository.yml
- dist/publish-crates-debian-main.mjs
- src/publish-crates-debian.ts
export the same key used to sign Release file
> chore: no need to use passphrase

- .github/workflows/release-crates-debian.yml
- .github/workflows/release-debian-repository.yml
- .github/workflows/test-gpg.yml
- dist/publish-crates-debian-main.mjs
- publish-crates-debian/action.yml
- src/publish-crates-debian.ts
> feat: add support to sign debian packages

- dist/set-git-branch-main.mjs
- src/set-git-branch.ts
Running it individually after each Cargo.toml change causes issues building zenoh-c opaque-types.
See https://github.com/eclipse-zenoh/ci/actions/runs/16573874180/job/46913910347
> fix: run cargo check after all updates

- dist/publish-crates-debian-main.mjs
- src/publish-crates-debian.ts
Fix https://github.com/eclipse-zenoh/zenoh-pico/actions/runs/17426673508/job/49475347649
> fix: filter out packages during installation test
