- .github/workflows/build-crates-artifacts.yml
Closes https://github.com/eclipse-zenoh/ci/issues/14.
> fix: Convert `input.exclude-build` to JSON object

- src/build-crates-artifacts.ts
- src/build-crates-debian.ts
Closes https://github.com/eclipse-zenoh/ci/issues/16.
> fix: Always install target when cross compiling

- src/build-crates-artifacts.ts
- src/build-crates-debian.ts
Resolves https://github.com/eclipse-zenoh/ci/issues/16.
We actually need to run rustup in the repo itself, otherwise the Rust toolchain file is not captured.
> fix: Install target from repo's Rust toolchain

- src/build-crates-debian.ts
Closes https://github.com/eclipse-zenoh/ci/issues/19.
> fix: Disable object file stripping in cargo-deb

- .github/workflows/release-crates-cargo.yml
- .github/workflows/release-crates-debian.yml
- .github/workflows/release-crates-eclipse.yml
- .github/workflows/release-crates-github.yml
- .github/workflows/release-crates-homebrew.yml
- build-crates-standalone/action.yml
Resolves https://github.com/eclipse-zenoh/ci/issues/25 (follow-up fix).
> fix: Incorrect script path in build-crates-standalone action

- dist/tag-crates-main.js
- src/tag-crates.ts
Resolves https://github.com/eclipse-zenoh/ci/issues/31.
> fix(tag-crates): Set `version` input to undefined when unspecified

- .github/workflows/release-crates-debian.yml
- .github/workflows/release-crates-dockerhub.yml
- .github/workflows/release-crates-eclipse.yml
- .github/workflows/release-crates-ghcr.yml
- .github/workflows/release-crates-github.yml
- .github/workflows/release-crates-homebrew.yml
Resolves https://github.com/eclipse-zenoh/ci/issues/31.
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds.
> fix(workflows/release-crates-*): Use `always()` to run publish jobs when `no-build` is set

- .github/workflows/release-crates-ghcr.yml
Resolves https://github.com/eclipse-zenoh/ci/issues/31.
> fix(workflows/release-crates-ghcr): Typo in `github-token` input

- dist/publish-crates-cargo-main.js
- dist/tag-crates-main.js
- src/command.ts
Fixes https://github.com/eclipse-zenoh/ci/issues/37.
Some commands like `cat` can output significant amounts of data on stdout. This is a hotfix to deal with this issue. I don't see an issue with increasing the `maxBuffer` for all commands except for more memory consumption (assuming Node.js allocates all of it ahead of spawning the process).
> fix: Increase child process `maxBuffer` size from 1MB to 10MB

- .github/workflows/build-crates-standalone.yml
> fix: Add default for `exclude-builds` in build-crates-standalone

- ci.config.json
- src/config.ts
Resolves https://github.com/eclipse-zenoh/ci/issues/23.
The config file is not taken into account. This will be done is subsequent PRs.
> feat: Add `ci.config.json` configuration file

- src/build-crates-debian.ts
> fix: Only use cross if a custom target is configured

- .github/workflows/release-crates-debian.yml
> fix: Add `installation-test` input in `release-crates-debian` workflow

- .github/workflows/branch-bump-tag-crates.yml
- .github/workflows/release-crates-cargo.yml
- .github/workflows/release-crates-debian.yml
> fix: Some typos in workflow inputs

- dist/create-release-branch-main.js
- src/create-release-branch.ts
> fix: Don't push the tag in `create-release-branch` action

- .github/workflows/branch-bump-tag-crates.yml
> fix: Get release version from branch step in `branch-tag-bump-crates`

- .github/workflows/branch-bump-tag-crates.yml
- bump-crates/action.yml
> fix: Require `branch` input in `bump-crates` action metadata

- dist/bump-crates-main.js
- src/bump-crates.ts
> fix: Clone release branch in bump-crates action

- dist/bump-crates-main.js
- src/bump-crates.ts
> fix: Early exit in `bump-crates` action when tag exists

- dist/bump-crates-main.js
- src/bump-crates.ts
> fix: Execute git-tag in repo in `bump-crates` actions

- build-crates-standalone/action.yml
- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/build-crates-standalone.ts
- src/cargo.ts
- src/git.ts
Resolves #69.
The following inputs are now non-required:
- target
- github-token
- branch
- version
> feat: Relax input requirements in `build-crates-standalone` action

- .github/workflows/release-crates-cargo.yml
Resolves #44.
Building Zenoh in cargo-publish by itself takes more storage space than is available out of the box on GitHub-hosted runners.
> fix: Maximize build space in publish-crates-cargo workflow

- .github/workflows/release-crates-cargo.yml
As of today, `df -h` returns the following:
- On ubuntu-latest: 18G (:
- On macos-latest: 69G
- On windows-latest: 72G
The windows-latest runner has better specs than the macos-latest runner, hence the choice.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
> fix: Run publish-crates-cargo on windows-latest

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
On Windows, Node.js uses cmd.exe as a shell, which doesn't treat single quotes as string delimiters.
> fix: Remove `'` in cargo module commands

- .github/workflows/release-crates-cargo.yml
After #76, cargo-publish fails because zenoh-plugin-rest's build script changes the source directory (it's not supposed to) and that makes the publishing fail (LF is changed to CRLF). 
This changes release-crates-cargo to use macOS because even though the file will be rewritten, it will stay identical.
Again, we can't use Ubuntu because the storage space is too low.
See https://github.com/eclipse-zenoh/zenoh/issues/897.
> fix: Don't run cargo-publish on Windows, use macOS

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
See https://github.com/eclipse-zenoh/zenoh-backend-filesystem/actions/runs/8538817359/job/23392233442.
```
error: failed to parse manifest at `/Users/runner/work/zenoh-backend-filesystem/zenoh-backend-filesystem/zenoh-backend-filesystem/Cargo.toml`
Caused by:
dependency (zenoh) specification is ambiguous. Only one of `git` or `registry` is allowed.
```
> fix: Delete git source when specifying registry in Cargo manifest

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
Pull request #80 deleted the `git` field but not the `branch` one.
> fix: Also delete branch when setting registry in Cargo manifest

- dist/publish-crates-cargo-main.js
- src/publish-crates-cargo.ts
See https://github.com/eclipse-zenoh/zenoh-backend-filesystem/actions/runs/8551849755/job/23431732477.
> fix: Allow dirty workspace in dry-run publishing

- .github/workflows/sync-lockfiles.yml
This moves the sync-lockfiles workflow from eclipse-zenoh/zenoh to eclipse-zenoh/ci.
Sister pull request: https://github.com/eclipse-zenoh/zenoh/pull/916.
> feat: Add sync-lockfiles workflow

- src/build-crates-standalone.ts
In #83 the repository was cloned in the current directory on GitHub Actions but the repo path variable was not updated.
> fix: Wrong repo path in build-crates-standalone

- .github/workflows/sync-lockfiles.yml
The amends #85 as it doesn't work when a pull request already exists but there are no new changes to push to it.
> fix: Enable auto-merge in sync-lockfiles when PR is not closed

- src/build-crates-standalone.ts
The cleanup function of build-crates-standalone fails on windows runners. It is not needed anyway.
> fix: Remove cleanup logic in build-crates-standalone

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/build-crates-debian.ts
- src/cargo.ts
Previously only cargo-deb metadata of the form `metadata.deb.*` and not `metadata.deb.variants.*` was supported.
> feat: Support multiple Debian package variants

- src/zip.ts
Previously only files were selectable when packaging artifacts from a build directory.
> feat: Support packaging directories

- .github/workflows/release-crates-eclipse.yml
> fix: Incorrect `ssh-host-path` in release-crates-eclipse workflow

- dist/bump-crates-main.js
- dist/create-release-branch-main.js
- dist/publish-crates-cargo-main.js
- src/bump-crates.ts
- src/command.ts
- src/create-release-branch.ts
Since this only concerns release branches and `main` has protection against `--force`, I think it's okay to allow for this as it makes life easier.
> fix: Override release branch and tag if they already exist

- dist/create-release-branch-main.js
- src/create-release-branch.ts
I've mistakenly used `git switch` to re-create the release branch from the default branch.
> fix: Use `git switch --force-create` to override existing branch

- .github/workflows/release-crates-eclipse.yml
- publish-crates-eclipse/action.yml
- publish-crates-github/action.yml
- src/publish-crates-eclipse.ts
- src/publish-crates-github.ts
This makes it possible to consume archives created outside `build-crates-{standalone,debian}` from `publish-crates-{eclipse,github}`.
Then `publish-crates-{eclipse,github}` should be renamed to something like `publish-{eclipse,github}` but that's for another day.
> feat: Support overriding eclipse/github archive patterns

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
The missing `\` makes the command string span two lines.
> fix: Typo in cargo-deb command

- dist/bump-crates-main.js
- src/bump-crates.ts
This only happens when the release tag and by extension the release branch already exist.
> fix: Force push release branch in bump-crates

- dist/bump-crates-main.js
- src/bump-crates.ts
It's simpler to force push every time, because throughout the code we don't fetch tags. Something to fix in the future.
> fix: Always force push release branch and tag

- .github/workflows/release-crates-github.yml
- publish-crates-github/action.yml
- src/publish-crates-github.ts
This was a copy-pasting error most likely.
> fix: Remove unecessary ssh passphrase/private-key in publish-crates-github

- dist/bump-crates-main.js
- dist/create-release-branch-main.js
- dist/publish-crates-cargo-main.js
- src/build-crates-debian.ts
- src/bump-crates.ts
- src/create-release-branch.ts
- src/publish-crates-cargo.ts
- src/publish-crates-debian.ts
- src/publish-crates-eclipse.ts
- src/publish-crates-github.ts
- src/publish-crates-homebrew.ts
This is unecessary on GitHub-hosted runners and occasionally causes spurious errors when no files are to be deleted or the I/O operation fails.
> fix: Remove file cleanup logic

- src/publish-crates-github.ts
Previously we just assumed that if the caller wants to release version `V`, then the repository should contains a tag `V-dev`. But this is very brittle and won't work for repositories that can't have `*-dev` versions like zenoh-c, zenoh-cpp and zenoh-pico (thanks CMake).
> fix: Use latest GitHub release tag as starting tag

- src/publish-crates-github.ts
In #104 I forgot to passe in the environment containing `GH_TOKEN`.
> fix: Add missing env option in gh-release-list command

- src/publish-crates-github.ts
In #104 I mistakenly removed the tag from the command.
> fix: Add missing tag input in gh-release-create

- dist/bump-crates-main.js
- dist/create-release-branch-main.js
- dist/publish-crates-cargo-main.js
- src/build-crates-debian.ts
- src/bump-crates.ts
- src/create-release-branch.ts
- src/publish-crates-cargo.ts
- src/publish-crates-debian.ts
- src/publish-crates-eclipse.ts
- src/publish-crates-homebrew.ts
This reverts commit 6cbbc64d4b03885925787dfea64693f22fd7b58e.
Actions create-release-branch and bump-crates actually relied on the repo being deleted afterwards.
However, this commit removes all instances of "rm -r *" as it can interfere with other actions.
> revert: Remove file cleanup logic

- __tests__/cargo.test.ts
- dist/bump-crates-main.js
- dist/create-release-branch-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
- src/command.ts
- Set `shell` to false in `command.exec` function
- Correct manifest path in `cargo.bumpDependencies`
- Add `cargo.bumpDependencies` tests
> fix: Set `shell` to false in `command.exec` function

- dist/publish-crates-cargo-main.js
- src/publish-crates-cargo.ts
Estuary should be killed in both live-runs and dry-runs.
> fix: Kill estuary during live-runs in publish-crates-cargo

- publish-crates-docker/action.yml
Fixes https://github.com/eclipse-zenoh/ci/issues/121.
> fix: Pass `BINARY` build-arg in publish-crates-docker action

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
This is not necessary and causes issues when a dependency is local to the workspace and Cargo refuses to have a `branch` field for them.
> fix: Disable setting of Cargo git source branches

- .github/workflows/release-crates-debian.yml
- publish-crates-debian/action.yml
- src/publish-crates-debian.ts
We now include the repo as part of the temporary
.Packages-$repo-$version file used to generate Packages.gz for the debian repository. This way the temporary .Packages file is not overwritten per package when the action runs causing Packages.gz to be built with missing Packages.
Fix #130
> Add repo as input for publish debian action

- publish-crates-docker/action.yml
Use inputs.version instead of version as that's the proper way. Fix failure like this: https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/actions/runs/8982804657/job/24671959155
> fix: typo in docker publish action

- src/publish-crates-debian.ts
- src/ssh.ts
input.repo comes from github.repository which means owner/repo We only need the repo name for the Packages file.
> Split input.repo to get only repo name.

- .github/workflows/check-labels.yml
Secrets are not automatically passed to reusable workflows from forked repos, but `github.token` is available and should be enough to perform the pr check.
> fix: update check-labels.yml to use GITHUB_TOKEN

- dist/create-release-branch-main.js
- src/create-release-branch.ts
Using `git push origin --delete refname`  apparently doesn't delete remote branch, so we strip the parts from the refname to get only the branch name. Fix #142 for real this time.
> fix: use branch name instead of full refname

- src/checksum.ts
- src/publish-crates-eclipse.ts
- src/publish-crates-homebrew.ts
> fix: Add sha256 sum file for eclipse

- .github/workflows/sync-toolchains.yml
This was mistakenly included in #3.
> fix: Remove `schedule` event trigger in sync-toolchains workflow

- .github/workflows/branch-bump-tag-crates.yml
- create-release-branch/action.yml
- dist/create-release-branch-main.js
- src/create-release-branch.ts
> feat: Add `branch` input to `create-release-branch` action

- dist/bump-crates-main.js
- dist/create-release-branch-main.js
- dist/publish-crates-cargo-main.js
- src/command.ts
- src/publish-crates-debian.ts
See for example any publish run: https://github.com/eclipse-zenoh/ci/actions/runs/9501265058/job/26186752103, the step that outputs the contents of all Packages files ends up breaking the github webui and makes the logs unreadable
> fix: don't output full .Packages-*

- dist/create-release-branch-main.js
- src/create-release-branch.ts
See https://github.com/eclipse-zenoh/zenoh/actions/runs/9539833719/job/26290670848.
> fix: Empty `branch` input in `create-release-branch`

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
Fixes #152.
The following script returns without error:
```bash
#!/usr/bin/env bash
set -e
dpkg --compare-versions 1.0.0~alpha.1-1 lt 1.0.0~alpha.2-1
dpkg --compare-versions 1.0.0~alpha.2-1 lt 1.0.0~beta.1-1
dpkg --compare-versions 1.0.0~beta.1-1 lt 1.0.0~beta.1-2
dpkg --compare-versions 1.0.0~beta.1-2 lt 1.0.0~rc.1-1
dpkg --compare-versions 1.0.0~rc.1-1 lt 1.0.0
```
> fix: Make release numbers follow the Debian Policy

- dist/create-release-branch-main.js
- src/create-release-branch.ts
- src/git.ts
If we don't fetch all remote branches, we cannot cleanup the dry-run history. This was a regression introduced in #156.
> fix: Fetch all release branches in `create-release-branch`

- .github/workflows/release-crates-cargo.yml
- dist/publish-crates-cargo-main.js
- publish-crates-cargo/action.yml
- src/publish-crates-cargo.ts
that way we don't need to update all the zenoh-* repos workflows
> fix: publication-test shouldn't be required

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
If a Cargo package depends on itself through `dev-dependencies`, the `cargo.packagesOrdered` function will loop forever.
> fix: Ignore workspace dev dependencies in `cargo.packages`

- .github/workflows/release-crates-cargo.yml
This reverts commit 207d35f1f1156a52251da54539f9eb77d82c2859.
> Revert "fix: re-enable cargo publication test"

- .github/workflows/build-crates-standalone.yml
macos-11 has been officially deprecated by github
> fix: Update workflow to use macos-12

- .github/workflows/sync-lockfiles-1.0.0.yml
They are not ready yet to be released with 1.0.0
> Don't sync zenoh-[java,kotlin]

- dist/create-release-branch-main.js
- src/create-release-branch.ts
Example failure: https://github.com/eclipse-zenoh/zenoh-python/actions/runs/9692165123/job/26744971281
> fix: don't fail workflow if tag delete fails

- .github/workflows/sync-toolchains.yml
When we update rust-toolchain.toml, we also need to update the Cargo.toml rust-version to match
> fix: Update Cargo.toml rust-version

- .github/workflows/sync-lockfiles-1.0.0.yml
zenoh-c has an additional Cargo.lock file in
build-resources/opaque-types/Cargo.lock that needs to be synced as well.
Fix #201
> fix: Update sync lock files script for zenoh-c

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
- src/publish-crates-cargo.ts
During release process, if something fails during the publication process, we can re-run the workflow skipping the packages that were already published.
Fix #183
> fix: allow re-runs of cargo publish to crates.io

- .github/workflows/sync-lockfiles-1.0.0.yml
- Enable syncing for kotlin and java
- don't download Cargo.lock file twice for zenoh-c, just copy it over to the additional location
> fix: additional fixes for sync lockfiles workflow

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
If the crate has never been published and cargo search returns nothing we should return false
> fix: verify cargo search returns results

- dist/create-release-branch-main.js
- src/create-release-branch.ts
During dry-run, the code ended up deleting the latest released tag.
See https://github.com/eclipse-zenoh/zenoh/actions/runs/10268819316/job/28412756096
> fix: don't delete tag while removing branches

- .github/workflows/sync-lockfiles-1.0.0.yml
Default inputs for scheduled workflow are not taken into account, so this fix guarantees we always use the dev/1.0.0 on scheduled runs.
> fix: scheduled sync-lockfile for 1.0.0 workflow

- .github/workflows/check-labels.yml
Before check-labels.yml would fail if the PR had no labels. Now we check if the PR has one of the required labels
> fix: Update check labels to verify specific ones

- .github/workflows/check-labels.yml
define a explicit github-token so we can re-use the bot token in forked repos
> fix: update check-labels secret

- .github/workflows/sync-lockfiles.yml
zenoh-c has an additional Cargo.lock file in
build-resources/opaque-types/Cargo.lock that needs to be synced as well.
> fix: update sync lock file script for zenoh-c

- src/publish-crates-debian.ts
attempt to fix error during publication of debian package
See https://github.com/eclipse-zenoh/zenoh-plugin-ros1/actions/runs/10852956160/job/30120604711
> fix: use shell to build Packages file

- .github/workflows/sync-lockfiles.yml
Instead of cargo check, use cargo clippy with all-features to get early warning
> fix: run cargo clippy with all-features

- .github/workflows/sync-lockfiles.yml
so cargo clippy can build everything to rectify the lock file
Try to avoid these errors: 
Cargo.lock sync failure [zenoh-plugin-dds](https://github.com/eclipse-zenoh/ci/actions/runs/10937948277/job/30364972553)
Cargo.lock sync failure [zenoh-plugin-ros2dds](https://github.com/eclipse-zenoh/ci/actions/runs/10937948277/job/30364973604)
> fix: install build dependencies

- .github/workflows/sync-lockfiles.yml
Rectifying the cargo lockfile with cargo clippy using all features causes an error. Remove the panic from the list before checking
See https://github.com/eclipse-zenoh/ci/actions/runs/10946354541/job/30392678442
> fix: disable panic for zenoh-c opaque-types

- ci.config.json
- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
- src/config.ts
- src/estuary.ts
Add option to installBinaryCached to install from git which allows installing estuary from our fork.
> fix: allow install cargo package from git

- .github/workflows/branch-bump-tag-crates.yml
- bump-crates/action.yml
- dist/bump-crates-main.js
- src/bump-crates.ts
This breaks the eclipse-zenoh/zenoh release workflow. Bindings have their own bump-and-tag.bash scripts which would need to updated individually.
> Don't tag dry-run releases

- .github/workflows/sync-lockfiles.yml
zenoh-dissector has been moved to https://github.com/eclipse-zenoh/zenoh-dissector. In any case, the old workflow didn't have the necessary permissions to commit on the previous org.
> Fix zenoh-dissector syncing

- .github/workflows/build-crates-standalone.yml
macos-12 is being deprecated. See https://github.com/actions/runner-images/issues/10721
> chore: update to latest macos-14 runner

- .github/workflows/sync-lockfiles.yml
Using short name makes it easier to read in the github web ui
> fix: shorten sync job name

- .github/workflows/release-crates-debian.yml
- .github/workflows/release-crates-eclipse.yml
- .github/workflows/release-crates-homebrew.yml
As per https://github.com/eclipse-zenoh/.eclipsefdn/pull/18, secrets were updated to follow eclipse foundation naming convention.
> chore: update secrets variable names

- .github/workflows/release-crates-debian.yml
- .github/workflows/release-crates-eclipse.yml
- .github/workflows/release-crates-homebrew.yml
Reverts eclipse-zenoh/ci#247
In https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5255#note_2858788 I requested the values to be reinstated so we are able to make the release on the 21st
> Revert "chore: update secrets variable names"

- .github/workflows/sync-lockfiles.yml
zenoh-plugin-ros1 is deprecated and won't be released with newer zenoh versions (>=1.0.0)
> chore: remove zenoh-plugin-ros1 from sync lock

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
- src/publish-crates-cargo.ts
cargo.isPublished() checks if the crate is already published in a given registry, without the env vars, it'll check against crates.io instead of estuary
> fix: pass env var to cargo.isPublished()

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- src/cargo.ts
- src/publish-crates-cargo.ts
If cargo search returns an error, assume the package is not published.
Should fix https://github.com/eclipse-zenoh/zenoh/actions/runs/13021834479/job/36324068463
> fix: don't check return value of cargo search

- .github/workflows/merge-release-branch.yml
- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- dist/set-git-branch-main.js
- src/cargo.ts
- src/set-git-branch.ts
- setup rust toolchain to `1.75.0` to avoid creating cargo lock files with version 4
- check if there are changes after `cargo.setGitBranch()`, if not, don't run git add
- fix GITHUB_OUTPUT and conditional for pr creation
- treat failure case during pr creation
- don't add git/branch to workspace deps
> Improvements to set-git-branch action

- .github/workflows/merge-release-branch.yml
Always capture the exit_code
Tries to fix error in annotating the PR after the creation step
> fix: better debug message

- .github/workflows/merge-release-branch.yml
- when gh pr create succeeds, we want to set the exit_code=0 
- if it fails, we want to set it to exit_code=1 but not fail the step
> fix: capture exit_code either way

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- dist/set-git-branch-main.js
- src/cargo.ts
make a copy of the options passed to isPublished() and then switch the check to false to avoid changing the original Options object passed which makes failures in the publish() function go unnoticed.
> fix: change isPublished to use copy of options

- dist/publish-crates-cargo-main.js
- src/publish-crates-cargo.ts
estuary publication is failing an blocking release. Besides estuary
as a pre release check has been less and less useful and it hasn't
been updated in ages.
> chore: disable estuary publication test

- dist/bump-crates-main.js
- src/bump-crates.ts
bump-deps-version is nil because it can't have default values in scheduled events. Set it to same as version in this case.
> fix: set bump-deps-version to same as version

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- dist/set-git-branch-main.js
- src/cargo.ts
In https://github.com/eclipse-zenoh/zenoh/pull/1846, zenoh `Cargo.toml` was updated to pin dependencies. This changes the `bumpDependencies()` code used by the release workflow actions to take into account the pin and keep it in place.
> fix: respect existing pin in cargo dependencies

- .github/workflows/sync-lockfiles.yml
See https://github.com/eclipse-zenoh/ci/actions/runs/13991693132/job/39176894796
> fix: add clippy to 1.75 toolchain

- dist/bump-crates-main.js
- dist/publish-crates-cargo-main.js
- dist/set-git-branch-main.js
- src/cargo.ts
- src/set-git-branch.ts
During release, cargo lock for some repositories were updated to version 4 which is incompatible with the rust 1.75 toolchain. This reverts them back to version 3.
> fix: correct cargo lock version in set-git-branch

- .github/workflows/build-crates-standalone.yml
windows-2022 runner still uses cmake 3.11 for now, and will unblock the 1.3.1 release for zenoh-plugin-ros2dds
> fix: use windows-2022 runner

- .github/workflows/build-crates-standalone.yml
Due to https://github.com/actions/runner-images/issues/11926 cmake was updated in the github hosted runners and we have to workaround the issue by installing cmake ourselves.
> fix: install cmake 3.31 before build crates

- dist/build-crates-debian-main.mjs
- dist/build-crates-standalone-main.mjs
- dist/bump-crates-main.mjs
- dist/publish-crates-cargo-main.mjs
- dist/publish-crates-debian-main.mjs
- dist/publish-crates-eclipse-main.mjs
- dist/publish-crates-github-main.mjs
- dist/publish-crates-homebrew-main.mjs
- dist/set-git-branch-main.mjs
- src/toml.ts
this way toml.get() can be used in boolean contexts
See https://github.com/eclipse-zenoh/ci/actions/runs/14259663835/job/39968446406#step:4:199, when toml.get() is used in a boolean context returning {}, it evaluates to true which is not what we expect.
> fix: toml.get() should return falsy value

- .github/workflows/merge-release-branch.yml
- dist/set-git-branch-main.mjs
- src/set-git-branch.ts
This avoid merging conflicts if the Cargo.lock changed before the merge-release-branch workflow is executed after release. We keep our changes to update the Cargo.lock to the main branch.
> fix: merge main into post-release branch

- .github/workflows/merge-release-branch.yml
Fix https://github.com/eclipse-zenoh/ci/actions/runs/14263671373/job/39980629158
> fix: skip setup of rust 1.75 for zenoh-dissector

- create-release-branch/action.yml
- dist/create-release-branch-main.mjs
- dist/set-registry-main.mjs
- src/create-release-branch.ts
Avoid breaking existing workflows, while still accepting a commit hash as input.
> fix: keep branch input in create-release-branch

- dist/build-crates-debian-main.mjs
- dist/build-crates-standalone-main.mjs
- dist/bump-crates-main.mjs
- dist/publish-crates-cargo-main.mjs
- dist/publish-crates-debian-main.mjs
- dist/publish-crates-eclipse-main.mjs
- dist/publish-crates-github-main.mjs
- dist/publish-crates-homebrew-main.mjs
- dist/set-git-branch-main.mjs
- dist/set-registry-main.mjs
- src/cargo.ts
cargo tooling used by numerous actions (toml-cli2, cross, cargo-deb) should be installed from crates.io.
> fix: force installBinaryCached to use crates.io

- bump-crates/action.yml
- dist/bump-crates-main.mjs
- src/bump-crates.ts
This way we default to 1.75.0 but allow consumers of bump-crates to override to an arbitrary toolchain (e.g. https://github.com/eclipse-zenoh/zenoh-dissector/actions/runs/15547337338/job/43771268582)
> fix: add toolchain input to bump crates

- ci.config.json
- dist/build-crates-debian-main.mjs
- dist/build-crates-standalone-main.mjs
- dist/bump-crates-main.mjs
- dist/publish-crates-cargo-main.mjs
- dist/publish-crates-debian-main.mjs
- dist/publish-crates-eclipse-main.mjs
- dist/publish-crates-github-main.mjs
- dist/publish-crates-homebrew-main.mjs
- dist/set-git-branch-main.mjs
- dist/set-registry-main.mjs
Possible fix for https://github.com/eclipse-zenoh/zenoh/actions/runs/16818562700/job/47640925943
> chore: update cargo-deb to 3.4.1

- bump-crates/action.yml
- dist/bump-crates-main.mjs
- src/bump-crates.ts
This allows to set different versions for dependencies, something like: 
```
bump-deps-patterns: |
^(zenoh-admin-client|zenoh_admin_interface)$
^zenoh(?!-admin-client|_admin_interface)[a-zA-Z0-9-_]*$
bump-deps-versions: |
${{ inputs.version }}
${{ inputs.zenoh_version }}
``` 
Useful for plugins like the zenoh-plugin-admin which has a different version than the zenoh version
> feat: allow bump-crates to set multi version deps

- dist/set-git-branch-main.mjs
- src/cargo.ts
Don't skip path/workspace deps since those also have registry key
> fix: always unset registry during set-git-branch
